name: Trigger Deploy

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: automated empty commit to trigger deploy"
          git push origin main